### ISSUE TITLE
STConvLSTM

### ISSUE THREAD

**Issue by vineeths96** [JaMesLiMers/Frame_Video_Prediction_Pytorch#3]
What is the STConvLSTM layer implemented [here](https://github.com/JaMesLiMers/Frame_Video_Prediction_Pytorch/blob/master/model/STconvLSTM.py)?

**Comment by JaMesLiMers** [comment]
Hello there! This is just an implement of "spatial-temporal convolutional LSTM" for testing the implementation. If it is useless for you, just ignore it :D.

**Comment by vineeths96** [comment]
I figured it would be the "Spatial-temporal convolutional LSTM", but it was written "ConvLSTM" throughout the docstrings. Thanks for the clarifications.

By the way, I was wondering if you have any sample images / pretrained model to visualize the performance of this network.
